# 通用配置文件

app:
  host: "0.0.0.0:8083"
  debug: true
  max_request: 1000 # 最大并发数量

email: # email 集合
  - user: "notice@dollarkiller.com"
    password: "%Y4I4qjlqKAy"
    host: "smtp.mail.ru"
    port: 465


