# 通用配置文件

app:
  host: "0.0.0.0:8083"
  debug: true
  max_request: 1000 # 最大并发数量
  key: "" # 秘钥

email: # email 集合
  - user: "a@a.com"
    password: "password"
    host: "smtp.mail.ru"
    port: 465


